### ISSUE TITLE
I could imagine a view (from the model-view-controller paradigm) that calls this function. Maybe add a function to get the figure? 

### ISSUE THREAD

**Issue by schuylerfried** [jonathanward/chchanges#11]
https://github.com/jonathanward/chchanges/blob/91420b0ce5ad10885bfb8ca9ffa33f781aa10369/chchanges/bayesian_online.py#L242

**Comment by jonward-rigetti** [comment]
what kind of signature did you have in mind?

**Comment by jonathanward** [comment]
All of the relevant state is internal to the posterior distribution, so I think it would be premature to separate things.
