### ISSUE TITLE
Consider dividing these classes up into different files or at least adding ##### to separate the sections

### ISSUE THREAD

**Issue by schuylerfried** [jonathanward/chchanges#12]
https://github.com/jonathanward/chchanges/blob/91420b0ce5ad10885bfb8ca9ffa33f781aa10369/chchanges/bayesian_online.py#L79

**Comment by jonward-rigetti** [comment]
fair point, I think that will be important once there is more than one detector/hazard/posterior

**Comment by jonathanward** [comment]
I'll close for now, and reopen later once its more pressing.
