### ISSUE TITLE
Might be useful to return the changepoint idx as well.. Idk how hard that would be

### ISSUE THREAD

**Issue by schuylerfried** [jonathanward/chchanges#14]
https://github.com/jonathanward/chchanges/blob/91420b0ce5ad10885bfb8ca9ffa33f781aa10369/chchanges/demos/variance.py#L40

**Comment by jonward-rigetti** [comment]
Do you mean moving `idxs_so_far` to be internal to the detector?
I could, but in general `idxs_so_far` might be `measurements_so_far` or `timestamps_so_far` and then you could just follow the same pattern.

**Comment by jonathanward** [comment]
after giving it some thought, I decided against it.
