### ISSUE TITLE
Would be nice to provide some examples on what these values should be 

### ISSUE THREAD

**Issue by schuylerfried** [jonathanward/chchanges#5]
https://github.com/jonathanward/chchanges/blob/91420b0ce5ad10885bfb8ca9ffa33f781aa10369/chchanges/bayesian_online.py#L89

**Comment by jonward-rigetti** [comment]
Do you think this is sufficiently covered in the demos and tests? 
I should add more documentation here, but I should also make a tutorial jupyter notebook which walks people through how to choose reasonable values.

**Comment by jonathanward** [comment]
expanded some docstrings, and provided default values.
