### ISSUE TITLE
If you're really concerned about space, consider float16s or float32s

### ISSUE THREAD

**Issue by schuylerfried** [jonathanward/chchanges#9]
https://github.com/jonathanward/chchanges/blob/91420b0ce5ad10885bfb8ca9ffa33f781aa10369/chchanges/bayesian_online.py#L119

**Comment by jonward-rigetti** [comment]
this is mostly a runtime optimization, so that we don't have to resize the array with a ton of appends.

**Comment by jonathanward** [comment]
Not particularly concerned rn, will close.
